version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A src.worker.celery_app worker --loglevel=info --pool=solo
    depends_on:
      - qdrant
      - redis
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TOKENIZERS_PARALLELISM=false
      - REDIS_URL=redis://redis:6379/0

  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
      - redis
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TOKENIZERS_PARALLELISM=false
      - PYTHONPATH=/app

volumes:
  qdrant-data:

 